### ISSUE TITLE
1D FFT on multidimensional array with arbitrary strides

### ISSUE THREAD

**Issue by fakufaku** [LCAV/mklfft#1]
For now, only contiguous up to 2D array are supported. Addind support for arbitrary strides would bring:
- support for arbitrary dimension and arbitrary axis
- support for arbitrary views, including non-contiguous

This problem comes from limitation of LIBMKL which DFTI_DISTANCE parameter is just a scalar. For arbitrary strides, it needs to be a 2D vector. Thus a for loop is required.

**Comment by oleksandr-pavlyk** [comment]
@fakufaku I have just stumbled upon this project. Glad you find Intel(R) MKL FFT useful in your project.

I would like to  draw your attention to https://github.com/IntelPython/mkl_fft, which implements the same idea, and does use `DFTI_DISTANCE` to reduce the number of calls to `dftiCompute` when performing 1D FFT along an axis of any nd array, provided datasets corresponding to these slices are equidistant. The aforementioned project is also [available on conda-forge](https://github.com/conda-forge/mkl_fft-feedstock), i.e. you can install it into your environment with `conda install -c conda-forge mkl_fft`, so directly from [Intel Distribution for Python](https://software.intel.com/en-us/distribution-for-python) channel with `conda install -c intel mkl_fft`.

The difference between two channels is, `mkl_fft` from Intel channel is compiled with Intel(R) C Compiler, while `mkl_fft` from conda-forge channel is compiled with GCC, clang or MSVC, depending on the platform.

**Comment by fakufaku** [comment]
Hi @oleksandr-pavlyk , good job with that! The mkl fft included so far with anaconda distribution did not cut it, which is whey we had to create this package!
Good job on creating the nice looking package! I will retire our module and add a pointer to your package!
